server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/demo
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    open-in-view: false

